// Starter script: convert a Kaggle-style Transfermarkt CSV into src/data/players.ts.
// Usage: node scripts/import-csv.mjs path/to/players.csv
// Adjust COLUMN names below to match your CSV's headers. Free, no network needed.
import { readFileSync, writeFileSync } from 'node:fs'

const COLUMN = {
  name: 'name',
  club: 'current_club_name',
  league: 'domestic_competition_id',
  nationality: 'country_of_citizenship',
  value: 'market_value_in_eur', // in raw euros; divided by 1e6 below
  position: 'sub_position',      // e.g. "Centre-Back", mapped to our codes below
}

const POS_MAP = {
  'Goalkeeper': 'GK',
  'Right-Back': 'RB', 'Left-Back': 'LB', 'Centre-Back': 'CB',
  'Defensive Midfield': 'CDM', 'Central Midfield': 'CM', 'Attacking Midfield': 'CAM',
  'Right Midfield': 'RM', 'Left Midfield': 'LM',
  'Right Winger': 'RW', 'Left Winger': 'LW',
  'Second Striker': 'CF', 'Centre-Forward': 'ST',
}

function parseCsv(text) {
  const [header, ...lines] = text.trim().split(/\r?\n/)
  const cols = header.split(',')
  return lines.map((line) => {
    // naive split; swap for a real CSV parser if fields contain commas
    const cells = line.split(',')
    return Object.fromEntries(cols.map((c, i) => [c, cells[i]]))
  })
}

const csvPath = process.argv[2]
if (!csvPath) { console.error('Usage: node scripts/import-csv.mjs path/to.csv'); process.exit(1) }

const rows = parseCsv(readFileSync(csvPath, 'utf8'))
const players = rows
  .map((r, i) => {
    const primary = POS_MAP[r[COLUMN.position]]
    const valueM = Number(r[COLUMN.value]) / 1e6
    if (!primary || !valueM) return null
    return {
      id: `p${i + 1}`,
      name: r[COLUMN.name],
      club: r[COLUMN.club] ?? '',
      league: r[COLUMN.league] ?? '',
      nationality: r[COLUMN.nationality] ?? '',
      value: Math.round(valueM * 10) / 10,
      rating: Math.min(99, Math.round(60 + valueM / 4)), // rough rating from value
      primaryPos: primary,
      eligiblePos: [primary], // extend with secondary positions if your CSV has them
    }
  })
  .filter(Boolean)

const out = `import type { Player } from '../types'\n\n// Auto-generated by scripts/import-csv.mjs\nexport const PLAYERS: Player[] = ${JSON.stringify(players, null, 2)}\n`
writeFileSync(new URL('../src/data/players.ts', import.meta.url), out)
console.log(`Wrote ${players.length} players to src/data/players.ts`)
